create extension if not exists pgcrypto;

do $$
begin
  if not exists (select 1 from pg_type where typname = 'case_status') then
    create type public.case_status as enum ('draft', 'submitted', 'archived');
  end if;
end $$;

create table if not exists public.bankruptcy_cases (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null check (char_length(title) between 1 and 120),
  chapter text not null check (chapter in ('7', '11', '12', '13')),
  filing_state text,
  filing_county text,
  status public.case_status not null default 'draft',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.case_responses (
  id uuid primary key default gen_random_uuid(),
  case_id uuid not null references public.bankruptcy_cases(id) on delete cascade,
  step_id text not null,
  payload jsonb not null default '{}'::jsonb,
  completed boolean not null default false,
  updated_at timestamptz not null default timezone('utc', now()),
  unique (case_id, step_id)
);

create table if not exists public.case_audit_events (
  id bigint generated by default as identity primary key,
  case_id uuid not null references public.bankruptcy_cases(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  action text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create or replace function public.set_row_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists trg_bankruptcy_cases_updated_at on public.bankruptcy_cases;
create trigger trg_bankruptcy_cases_updated_at
before update on public.bankruptcy_cases
for each row
execute function public.set_row_updated_at();

drop trigger if exists trg_case_responses_updated_at on public.case_responses;
create trigger trg_case_responses_updated_at
before update on public.case_responses
for each row
execute function public.set_row_updated_at();

alter table public.bankruptcy_cases enable row level security;
alter table public.case_responses enable row level security;
alter table public.case_audit_events enable row level security;

drop policy if exists "Users can select own bankruptcy cases" on public.bankruptcy_cases;
create policy "Users can select own bankruptcy cases"
on public.bankruptcy_cases
for select
using (auth.uid() = user_id);

drop policy if exists "Users can insert own bankruptcy cases" on public.bankruptcy_cases;
create policy "Users can insert own bankruptcy cases"
on public.bankruptcy_cases
for insert
with check (auth.uid() = user_id);

drop policy if exists "Users can update own bankruptcy cases" on public.bankruptcy_cases;
create policy "Users can update own bankruptcy cases"
on public.bankruptcy_cases
for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users can delete own bankruptcy cases" on public.bankruptcy_cases;
create policy "Users can delete own bankruptcy cases"
on public.bankruptcy_cases
for delete
using (auth.uid() = user_id);

drop policy if exists "Users can select own case responses" on public.case_responses;
create policy "Users can select own case responses"
on public.case_responses
for select
using (
  exists (
    select 1
    from public.bankruptcy_cases bc
    where bc.id = case_id
      and bc.user_id = auth.uid()
  )
);

drop policy if exists "Users can insert own case responses" on public.case_responses;
create policy "Users can insert own case responses"
on public.case_responses
for insert
with check (
  exists (
    select 1
    from public.bankruptcy_cases bc
    where bc.id = case_id
      and bc.user_id = auth.uid()
  )
);

drop policy if exists "Users can update own case responses" on public.case_responses;
create policy "Users can update own case responses"
on public.case_responses
for update
using (
  exists (
    select 1
    from public.bankruptcy_cases bc
    where bc.id = case_id
      and bc.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.bankruptcy_cases bc
    where bc.id = case_id
      and bc.user_id = auth.uid()
  )
);

drop policy if exists "Users can delete own case responses" on public.case_responses;
create policy "Users can delete own case responses"
on public.case_responses
for delete
using (
  exists (
    select 1
    from public.bankruptcy_cases bc
    where bc.id = case_id
      and bc.user_id = auth.uid()
  )
);

drop policy if exists "Users can select own case audit events" on public.case_audit_events;
create policy "Users can select own case audit events"
on public.case_audit_events
for select
using (auth.uid() = user_id);

drop policy if exists "Users can insert own case audit events" on public.case_audit_events;
create policy "Users can insert own case audit events"
on public.case_audit_events
for insert
with check (
  auth.uid() = user_id
  and exists (
    select 1
    from public.bankruptcy_cases bc
    where bc.id = case_id
      and bc.user_id = auth.uid()
  )
);

create index if not exists idx_bankruptcy_cases_user_id on public.bankruptcy_cases(user_id);
create index if not exists idx_case_responses_case_id on public.case_responses(case_id);
create index if not exists idx_case_audit_events_case_id on public.case_audit_events(case_id);
create index if not exists idx_case_audit_events_user_id on public.case_audit_events(user_id);

revoke all on public.bankruptcy_cases from anon;
revoke all on public.case_responses from anon;
revoke all on public.case_audit_events from anon;

grant select, insert, update, delete on public.bankruptcy_cases to authenticated;
grant select, insert, update, delete on public.case_responses to authenticated;
grant select, insert on public.case_audit_events to authenticated;
grant usage, select on sequence public.case_audit_events_id_seq to authenticated;

create or replace function public.case_packet(case_uuid uuid)
returns jsonb
language sql
security invoker
set search_path = public
as $$
  with case_data as (
    select *
    from public.bankruptcy_cases
    where id = case_uuid
      and user_id = auth.uid()
  ),
  response_data as (
    select step_id, payload, completed, updated_at
    from public.case_responses
    where case_id = case_uuid
  )
  select jsonb_build_object(
    'generated_at', timezone('utc', now()),
    'case', to_jsonb(case_data),
    'responses', coalesce(
      (
        select jsonb_agg(
          jsonb_build_object(
            'step_id', step_id,
            'payload', payload,
            'completed', completed,
            'updated_at', updated_at
          )
        )
        from response_data
      ),
      '[]'::jsonb
    )
  )
  from case_data;
$$;

grant execute on function public.case_packet(uuid) to authenticated;
